micronaut:
  application:
    name: catalogue
    instance:
      id: ${random.shortuuid}
netty:
  default:
    allocator:
      max-order: 3
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
db:
  name: 'catalogue'
  collection: 'products'