micronaut:
  application:
    name: catalogue
    instance:
      id: ${random.shortuuid}
consul:
  client:
    default-zone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
    registration:
      enabled: true
      prefer-ip-address: true
      health-path: /health
      check:
        http: true
    health-check: true
netty:
  default:
    allocator:
      max-order: 3
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
db:
  name: 'catalogue'
  collection: 'products'
endpoints:
  health:
    enabled: true
    sensitive: false